// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Note struct {
	UserID int64
	ID     int64
	Title  pgtype.Text
	Body   pgtype.Text
}
