// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (user_id, title, body) VALUES ($1, $2, $3) RETURNING id
`

type CreateNoteParams struct {
	UserID int64
	Title  pgtype.Text
	Body   pgtype.Text
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (int64, error) {
	row := q.db.QueryRow(ctx, createNote, arg.UserID, arg.Title, arg.Body)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteNote = `-- name: DeleteNote :exec
DELETE FROM notes WHERE id = $1
`

func (q *Queries) DeleteNote(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteNote, id)
	return err
}

const getNoteByID = `-- name: GetNoteByID :one
SELECT id, title, body FROM notes WHERE id = $1
`

type GetNoteByIDRow struct {
	ID    int64
	Title pgtype.Text
	Body  pgtype.Text
}

func (q *Queries) GetNoteByID(ctx context.Context, id int64) (GetNoteByIDRow, error) {
	row := q.db.QueryRow(ctx, getNoteByID, id)
	var i GetNoteByIDRow
	err := row.Scan(&i.ID, &i.Title, &i.Body)
	return i, err
}

const updateNote = `-- name: UpdateNote :exec
UPDATE notes SET title = $2, body = $3 WHERE id = $1
`

type UpdateNoteParams struct {
	ID    int64
	Title pgtype.Text
	Body  pgtype.Text
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) error {
	_, err := q.db.Exec(ctx, updateNote, arg.ID, arg.Title, arg.Body)
	return err
}
